---
- name: "Hello World Webserver Deploy"
  hosts: web
  tags: deploy

  tasks:
    - name: setup latest nginx
      apt: name=nginx state=latest
      become: yes
    - name: start nginx
      service:
        name: nginx
        state: started 
      become: yes
    - name: unlink default configs
      file: 
        state: absent
        path: /etc/nginx/conf.d/default
    - name: add server config
      copy:
        src: hello_world.conf
        dest: /etc/nginx/conf.d/
    - name: create hello world serving directory
      file:
        path: /var/www/hello_world
        state: directory
    - name: add static page
      copy:
        src: index.html
        dest: /var/www/hello_world/
    - name: restart nginx
      service: 
        name: nginx
        state: restarted
      become: yes


- name: Hello Word Webserver Teardown
  hosts: web
  tags: undeploy

  tasks:
    - name: stop nginx webserver
      service:
        name: nginx
        state: stopped
      become: yes
    - name: make sure nginx is not installed
      apt: name=nginx state=absent purge=yes
      become: yes